musicapp/config/routes.rb
Rails.application.routes.draw do

  resources :albums_tests
  resources :tests
  resources :albums
  resources :users

  get 'login' => 'sessions#login', :as => 'log_in' 
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  post 'login' => 'sessions#create', :as => 'create_login'

  get 'tests/:id/play' => 'tests#play', :as => 'test_play' 
  post 'tests/:id/play' => 'tests#submit', :as => 'test_submit'
  get 'tests/:id/album' => 'tests#add_album', :as => 'test_add_album'
  post 'tests/:id/album' => 'tests#create_album', :as => 'test_create_album'
  delete 'tests/:id/album/:album_id' => 'tests#delete_album', :as => 'test_delete_album'

  root 'welcome#index'

end

musicapp/app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt
  
  has_many :tests, dependent: :destroy
  validates :name, presence: true
  validates :password, presence: true
  validate :cap_name

  def cap_name
    unless name.nil? || name.empty? || name[0].capitalize == name[0]
      errors.add(:name, 'is not capitalized')
    end
  end

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end


end

musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    reset_session
    @user = User.new
  end
  
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.high_score = 0
    @user.password = params[:user][:password]

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    reset_session
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password_hash)
    end
end

musicapp/app/helpers/users_helper.rb
module UsersHelper
end

musicapp/app/views/users/_form.html.erb
<font size="1"><%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %></font>

musicapp/app/views/users/_form2.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

musicapp/app/views/users/edit.html.erb
<%= render 'form' %>

<font size="1"><%= link_to 'Back', user_path %></font>

musicapp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<font size="1">
<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>High Score </th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>    
    <% @users.order(high_score: :desc).each do |user| %>
      <tr>
        <td><%= user.name %></td>
	<td><%= user.high_score %></td>
	<td><%= link_to 'Profile', user %></td>
      </tr>
    <% end %>
  </tbody>
</table></font>

<br>

musicapp/app/views/users/login.html.erb
<h3>Log in User</h3>

<%= render 'form2' %>

<%= link_to 'Back', users_path %>

musicapp/app/views/users/new.html.erb
<h4>New User</h4>

<%= render 'form' %> 

musicapp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>

<h4> <%= @user.name + "'s Profile" %></h4>

<font size=1><table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% if @user.tests.empty? %> 
    <tr> 
      <td> No tests here! </td>
    </tr>
    <% else %>
    <% @user.tests.each do |test| %>
      <tr>
        <td><%= link_to test.name, test_path %></td>
	<% if test.albums.empty? %>
	<td> No albums </td>
	<% else %>
	<td><%= link_to 'Play', test_play_path(test) %></td>
<% end %>
	<% if logged_in? && session[:user_id] == @user.id %>
	<td> <%= link_to 'Add Album', test_add_album_path(test) %> </td>
        <td><%= link_to 'Edit', edit_test_path(test) %></td>
        <td><%= link_to 'Delete', test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table></font>

<font size=1>
<% if logged_in? && session[:user_id] == @user.id %>
<%= link_to 'Edit Profile', edit_user_path(@user) %> | 
<%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure? ' } %>
<% end %></font>

</p>