musicapp/config/routes.rb
Rails.application.routes.draw do

  resources :albums_tests
  resources :tests
  resources :albums
  resources :users

  get 'login' => 'sessions#login', :as => 'log_in' 
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  post 'login' => 'sessions#create', :as => 'create_login'

  get 'tests/:id/play' => 'tests#play', :as => 'test_play' 
  post 'tests/:id/play' => 'tests#submit', :as => 'test_submit'
  get 'tests/:id/album' => 'tests#add_album', :as => 'test_add_album'
  post 'tests/:id/album' => 'tests#create_album', :as => 'test_create_album'
  delete 'tests/:id/album/:album_id' => 'tests#delete_album', :as => 'test_delete_album'

  root 'welcome#index'

end

musicapp/app/models/albums_test.rb
class AlbumsTest < ActiveRecord::Base
  belongs_to :album
  belongs_to :test
end

musicapp/app/controllers/albums_tests_controller.rb
class AlbumsTestsController < ApplicationController
  before_action :set_songs_test, only: [:show, :edit, :update, :destroy]

  # GET /songs_tests
  # GET /songs_tests.json
  def index
    @songs_tests = AlbumsTest.all
  end

  # GET /songs_tests/1
  # GET /songs_tests/1.json
  def show
  end

  # GET /songs_tests/new
  def new
    @songs_test = AlbumsTest.new
  end

  # GET /songs_tests/1/edit
  def edit
  end

  # POST /songs_tests
  # POST /songs_tests.json
  def create
    @songs_test = AlbumsTest.new(songs_test_params)

    respond_to do |format|
      if @songs_test.save
        format.html { redirect_to @songs_test, notice: 'Albums test was successfully created.' }
        format.json { render :show, status: :created, location: @songs_test }
      else
        format.html { render :new }
        format.json { render json: @songs_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs_tests/1
  # PATCH/PUT /songs_tests/1.json
  def update
    respond_to do |format|
      if @songs_test.update(songs_test_params)
        format.html { redirect_to @songs_test, notice: 'Albums test was successfully updated.' }
        format.json { render :show, status: :ok, location: @songs_test }
      else
        format.html { render :edit }
        format.json { render json: @songs_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs_tests/1
  # DELETE /songs_tests/1.json
  def destroy
    @songs_test.destroy
    respond_to do |format|
      format.html { redirect_to songs_tests_url, notice: 'Albums test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_songs_test
      @songs_test = AlbumsTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def albums_test_params
      params.require(:albums_test).permit(:album_id, :test_id)
    end
end

musicapp/app/views/albums_tests/_form.html.erb
<%= form_for(@albums_test) do |f| %>
  <% if @albums_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@albums_test.errors.count, "error") %> prohibited this albums_test from being saved:</h2>

      <ul>
      <% @albums_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_id %><br>
    <%= f.text_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.text_field :test_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

musicapp/app/views/albums_tests/edit.html.erb
<h1>Editing Albums Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @albums_test %> |
<%= link_to 'Back', albums_tests_path %>

musicapp/app/views/albums_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums Tests</h1>

<table>
  <thead>
    <tr>
      <th>Album</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums_tests.each do |albums_test| %>
      <tr>
        <td><%= albums_test.album %></td>
        <td><%= albums_test.test %></td>
        <td><%= link_to 'Show', albums_test %></td>
        <td><%= link_to 'Edit', edit_albums_test_path(albums_test) %></td>
        <td><%= link_to 'Destroy', albums_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Albums test', new_albums_test_path %>

musicapp/app/views/albums_tests/new.html.erb
<h1>New Albums Test</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_tests_path %>

musicapp/app/views/albums_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @albums_test.album %>
</p>

<p>
  <strong>Test:</strong>
  <%= @albums_test.test %>
</p>

<%= link_to 'Edit', edit_albums_test_path(@albums_test) %> |
<%= link_to 'Back', albums_tests_path %>