musicapp/config/routes.rb
Rails.application.routes.draw do

  resources :albums_tests
  resources :tests
  resources :albums
  resources :users

  get 'login' => 'sessions#login', :as => 'log_in' 
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  post 'login' => 'sessions#create', :as => 'create_login'

  get 'tests/:id/play' => 'tests#play', :as => 'test_play' 
  post 'tests/:id/play' => 'tests#submit', :as => 'test_submit'
  get 'tests/:id/album' => 'tests#add_album', :as => 'test_add_album'
  post 'tests/:id/album' => 'tests#create_album', :as => 'test_create_album'
  delete 'tests/:id/album/:album_id' => 'tests#delete_album', :as => 'test_delete_album'

  root 'welcome#index'

end

musicapp/app/models/album.rb
require 'open-uri'
require 'rest-client'
require 'json'


class Album < ActiveRecord::Base

  has_many :album_tests, dependent: :destroy
  has_many :tests, through: :albums_tests

  validates :name, presence: true
  validates :artist, presence: true, uniqueness: { scope: :name, message: "Name and artist should be unique" }

  validate :cap_name

  validate :cap_artist

  validate :in_spotify

  grant = Base64.encode64("4426f03c25e345a0b604f2d4f19c1678:8a034e7a27e44e4ea0d520de19869f47").delete("\n")
  respond = RestClient.post('https://accounts.spotify.com/api/token',
                       {'grant_type' => 'client_credentials'},
                       {"Authorization" => "Basic #{grant}"})
  token_ext =  respond.split(',')
  token_ext2 = token_ext[0].split(':')
  only_token = token_ext2[1].delete_prefix('"').delete_suffix('"')
  $header = {'Authorization': "Bearer #{only_token}"}

  def cap_name
    unless name.nil? || name.empty? || name[0].capitalize == name[0]
      errors.add(:name, 'is not capitalized')
    end
  end

  def cap_artist
    unless artist.nil? || artist.empty? || artist[0].capitalize == artist[0]
      errors.add(:artist, 'is not capitalized')
    end
  end


  def in_spotify
    if name.nil? || name.empty?
      errors.add(:album, 'does not exist in Spotify')
    else
      my_hash = JSON.parse(RestClient.get("https://api.spotify.com/v1/search?q=#{album_search}&type=album", $header))
      if my_hash['albums']['items'].empty?
        errors.add(:album, 'does not exist in Spotify')
      end
    end
  end
  
  def album_format 
    name + " by " + artist 
  end

  def rand_four
    ans = [ self ]    

    while ans.size < 4 
      offset = rand(Album.count)
      rand_album = Album.offset(rand(Album.count)).first
      ans << rand_album unless ans.include?(rand_album)
    end

    ans.shuffle
  end

  def album_eq(album)
    equal?(album) ? "true" : "false"
  end

  def spotify_uri
    my_hash = JSON.parse(RestClient.get("https://api.spotify.com/v1/search?q=#{album_search}&type=album", $header))
    p my_hash['albums']['items'][0]['images'][0]['url']
  end


  def album_search
    artist.tr(' ', '+') + '+' + name.tr(' ', '+')
  end

end

musicapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :artist)
    end
end

musicapp/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

musicapp/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

musicapp/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.id %></td>
        <td><%= album.artist %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

musicapp/app/views/albums/new.html.erb
<h3>New Album</h3>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

musicapp/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>