musicapp/config/routes.rb
Rails.application.routes.draw do

  resources :albums_tests
  resources :tests
  resources :albums
  resources :users

  get 'login' => 'sessions#login', :as => 'log_in' 
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  post 'login' => 'sessions#create', :as => 'create_login'

  get 'tests/:id/play' => 'tests#play', :as => 'test_play' 
  post 'tests/:id/play' => 'tests#submit', :as => 'test_submit'
  get 'tests/:id/album' => 'tests#add_album', :as => 'test_add_album'
  post 'tests/:id/album' => 'tests#create_album', :as => 'test_create_album'
  delete 'tests/:id/album/:album_id' => 'tests#delete_album', :as => 'test_delete_album'

  root 'welcome#index'

end

musicapp/app/views/layouts/_nav.html.erb
<body> 
<nav class="navbar navbar-default navbar-fixed-top" >
  <a class="navbar-brand" href="/">Evan's Album Quizzes</a> 
  <a class="nav-item" href="/tests">Play</a> |
  <a class="nav-item" href="/users">High Scores</a> |
  <% if logged_in? && session[:user_id] == current_user.id %>
  
  <%= link_to current_user.name, user_path(current_user.id) %> |
  <%= link_to 'Log out', log_out_path %> 
  <% else %> 
  <%= link_to 'Log in', log_in_path %> |
  <%= link_to 'Sign up', new_user_path %>
  <% end %>
  <span class="nav-sessions">
  </span>
</nav>
</body>

musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top:50px">

<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>